import { Definition, Definitions, v2 } from "../../engine/core.ts";
import { BulletDefinition, type TankDefinition } from "./entity_datas.ts";
export const TanksBullet:Record<string,BulletDefinition>={
    default:{
        damage:1,
        health:0.5,
        radius:0.75,
        speed:20,
    },
    default_fast:{
        damage:0.5,
        health:1,
        radius:0.75,
        speed:35,
    },
    default_powered:{
        damage:2,
        health:3,
        radius:0.75,
        speed:25,
    },
    default_medium:{
        damage:0.6,
        health:1,
        radius:0.75,
        speed:20,
    },
    default_drone:{
        type:"drone",
        sides:3,
        damage:1,
        health:2,
        radius:0.5,
        speed:15,
    },
}
export const Tanks=new Definitions<TankDefinition&Definition,{}>()
Tanks.insert(
    {
        idString:"initial",
        name:"Initial",
        tank:{
            evolution:[
                {id:"double_shot",level:12},
                {id:"scout",level:12},
                {id:"backshot",level:12},
            ],
        },
        barrels:[
            {
                physical:{

                },
                shoot:{
                    delay:0.7,
                    recoil:0.5,
                    spread:1,
                    bullet:TanksBullet.default,
                }
            }
        ],
        physical:{

        }
    },
    // Level 12
    {
        name:"Double Shot",
        idString:"double_shot",
        tank:{
            evolution:[
                {id:"quad_shot",level:25}
            ]
        },
        barrels:[
            {
                physical:{
                    position:v2.new(0,-0.8),
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:2,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:2,
                    bullet:TanksBullet.default_medium,
                }
            }
        ],
        physical:{

        }
    },
    {
        name:"Scout",
        idString:"scout",
        tank:{
            evolution:[
                {id:"evoker",level:25},
                {id:"big_shot",level:25},
            ]
        },
        barrels:[
            {
                physical:{
                    size:v2(4,1.5)
                },
                shoot:{
                    delay:1,
                    recoil:1,
                    spread:0.1,
                    bullet:TanksBullet.default,
                }
            }
        ],
        physical:{

        }
    },
    {
        name:"Backshot",
        idString:"backshot",
        tank:{
            evolution:[
                {id:"dual_backshot",level:25},
            ]
        },
        barrels:[
            {
                physical:{
                },
                shoot:{
                    delay:1,
                    recoil:1,
                    spread:0.1,
                    bullet:TanksBullet.default_fast,
                }
            },
            {
                physical:{
                    size:v2(3,1.5),
                    direction:180
                },
                shoot:{
                    delay:1,
                    spread:1,
                    bullet:TanksBullet.default,
                }
            }
        ],
        physical:{

        }
    },
    // Level 25
    {
        name:"Quad Shot",
        idString:"quad_shot",
        tank:{
            evolution:[
                {id:"hexa_shot",level:37}
            ]
        },
        barrels:[
            {
                physical:{
                    position:v2.new(0,-0.8),
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:2,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:2,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:180
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:2,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:180
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:2,
                    bullet:TanksBullet.default_medium,
                }
            }
        ],
        physical:{
        }
    },
    {
        name:"Big Shot",
        idString:"big_shot",
        tank:{
            evolution:[
                {id:"mega_shot",level:37}
            ]
        },
        barrels:[
            {
                physical:{
                    size:v2.new(3.5,3),
                },
                shoot:{
                    delay:2,
                    recoil:3,
                    spread:1,
                    bullet:{
                        radius:1.4,
                        damage:4,
                        health:5.5,
                        speed:10,
                    },
                }
            }
        ],
        physical:{

        }
    },
    {
        name:"Evoker",
        idString:"evoker",
        tank:{
            
        },
        barrels:[
            {
                physical:{
                    size:v2.new(3,3),
                },
                shoot:{
                    limit:6,
                    delay:1.5,
                    recoil:0.5,
                    spread:1,
                    bullet:TanksBullet.default_drone,
                }
            }
        ],
        physical:{

        }
    },
    {
        name:"Dual Backshot",
        idString:"dual_backshot",
        physical:{
        },
        tank:{
            evolution:[
                {id:"quad_backshot",level:37},
            ]
        },
        barrels:[
            //Front
            {
                physical:{
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default_fast
                }
            },
            //Large
            {
                physical:{
                    direction:145
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
            {
                physical:{
                    direction:-145
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
        ]
    },
    // Level 37
    {
        name:"Hexa Shot",
        idString:"hexa_shot",
        tank:{
            evolution:[
                {id:"octo_shot",level:50}
            ]
        },
        barrels:[
            // Front
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:0
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:0
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            //Bottom
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:120
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:120
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            //Top
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:-120
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:-120
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            }
        ],
        physical:{
        }
    },
    {
        name:"Mega Shot",
        idString:"mega_shot",
        tank:{
            
        },
        barrels:[
            {
                physical:{
                    size:v2.new(3.5,4),
                },
                shoot:{
                    delay:2.5,
                    recoil:4,
                    spread:1,
                    bullet:{
                        radius:2,
                        damage:7.5,
                        health:7.5,
                        speed:10,
                    },
                }
            }
        ],
        physical:{

        }
    },
    {
        name:"Quad Backshot",
        idString:"quad_backshot",
        physical:{

        },
        tank:{

        },
        barrels:[
            //Front
            {
                physical:{
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
            //Small
            {
                physical:{
                    size:v2(3,1.5),
                    direction:130
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
            {
                physical:{
                    size:v2(3,1.5),
                    direction:-130
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
            //Large
            {
                physical:{
                    direction:145
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
            {
                physical:{
                    direction:-145
                },
                shoot:{
                    delay:1,
                    recoil:1.5,
                    bullet:TanksBullet.default
                }
            },
        ]
    },
    // Level 50
    {
        name:"Octo Shot",
        idString:"octo_shot",
        tank:{
        },
        barrels:[
            // Front
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:0
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:0
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            //Bottom
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:90
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:90
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            //Top
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:-90
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:-90
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            //Back
            {
                physical:{
                    position:v2.new(0,-0.8),
                    direction:-180
                },
                shoot:{
                    delay:1,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            },
            {
                physical:{
                    position:v2.new(0,0.8),
                    direction:-180
                },
                shoot:{
                    delay:0.7,
                    recoil:0.25,
                    spread:1,
                    bullet:TanksBullet.default_medium,
                }
            }
        ],
        physical:{
        }
    },
)